services:
  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: file:./prisma/dev.db
      JWT_SECRET: change-me-in-production-please
      JWT_EXPIRES_IN: 12h
      NEXT_PUBLIC_APP_NAME: HIMS OPD
      NEXT_PUBLIC_APP_URL: http://localhost:3100
      NODE_ENV: production
      PORT: 3100
    ports:
      - "3100:3100"
    volumes:
      - hims_data:/app/prisma

volumes:
  hims_data:
